num1 = int(input('Digite o seu primeiro número:'))
num2 = int(input('Digite o seu segundo número:'))
num3 = int(input('Digite o seu terceiro número'))
num4 = int(input('Digite o seu quarto número:'))
num5 = int(input('Digite o seu quinto número:'))
menor = min(num1, num2, num3, num4, num5)
maior = max(num1, num2, num3, num4, num5)
print(f'O primeiro número é:{num1}')
print(f'O segundo número é:{num2}')
print(f'O terceiro número é:{num3}')
print(f'O quarto número é:{num4}')
print(f'O quinto número é:{num5}')
print(f'O menor número é:{menor}')
print(f'O maior número é:{maior}')
